# message type to describe the tracking information of the blocks
# to be published as a topic

float64 x_r1  # x coordinate in the world
float64 y_r1  # y coordinate in the world
float64 z_r1  # z coordinate in the world
float64 error_x_r1
float64 error_y_r1
float64 error_z_r1
float64 x_r2  # x coordinate in the world
float64 y_r2  # y coordinate in the world
float64 z_r2  # z coordinate in the world
float64 error_x_r2
float64 error_y_r2
float64 error_z_r2
bool flag1_r1
bool flag2_r1
bool flag3_r1
bool flag1_r2
bool flag2_r2
bool flag3_r2

